// Example queries for Satoshi AI. Each category is shown as a header in the UI, with queries as clickable suggestions.
// To extend: Add new categories or queries as needed. Keep queries actionable, concise, and focused on real-time, data-driven insights.

export const SATOSHI_EXAMPLE_QUERIES_CATEGORIZED = {
  'Beginner Onboarding': [
    'Explain Bitcoin to a complete beginner. Use a real-world analogy and highlight why it matters in today’s economy.',
    'Compare Bitcoin to stocks and gold. What are the key differences in risk, return, and use case?',
    'List the safest ways to buy and store BTC in 2025. Include recommended platforms and wallet types.',
    'Show how to set up real-time alerts for Bitcoin price and news using free tools.',
  ],
  'Price & Performance': [
    'List the live prices and 24h % change for Bitcoin, Ethereum, and Solana. Highlight which is outperforming today.',
    'Identify any crypto that hit a new all-time high in the last 24 hours. Summarize the news or catalyst behind the move.',
    'Show the top 5 crypto gainers and losers today. For each, provide a one-sentence reason for the move.',
    'Which asset in the crypto top 100 had the biggest price drop today? What news or data explains the decline?',
    'Compare the volatility of Tesla and Bitcoin over the last quarter. Which was riskier for investors?',
    'List the top S&P500 gainers this week and compare their returns to BTC. Highlight any sector trends.',
    'What is the current price of MSTR? Compare its YTD performance to Bitcoin and explain any divergence.',
  ],
  'Stock & Equity Analysis': [
    'Summarize the latest NVDA earnings report. Compare its stock performance to BTC over the same period.',
    'List all stocks that had IPOs this month. For each, show their return since IPO and compare to Bitcoin.',
    'Analyze insider sentiment for Apple. How does it correlate with recent BTC price action?',
    'Summarize the latest analyst recommendations for Coinbase. Compare COIN’s performance to BTC YTD.',
    'Show the current price target consensus for MicroStrategy. How does analyst sentiment compare to Bitcoin’s outlook?',
    'List the most recent institutional holdings changes for NVDA. Benchmark their returns vs BTC.',
    'Summarize the latest company news for Tesla. Compare TSLA’s YTD return to BTC and explain any major moves.',
  ],
  'Macro & Cross-Asset': [
    'Analyze Bitcoin’s price reaction to today’s Fed announcement. Was the move in line with other risk assets?',
    'Compare today’s performance of gold, S&P 500, and BTC. Which asset led and why?',
    'What is the current DXY (US Dollar Index)? Explain how its movement is impacting BTC price today.',
    'Correlate today’s Bitcoin price action with the latest CPI and unemployment data. What macro trends are driving the market?',
    'Calculate the Sharpe ratio for BTC, S&P 500, and gold over the last 90 days. Which asset offered the best risk-adjusted return?',
    'Summarize the current macro outlook for risk assets. How is BTC positioned compared to stocks and gold?',
  ],
  'On-Chain & Network': [
    'Report the current Bitcoin network hash rate and difficulty. What does this signal about miner activity?',
    'How many BTC were moved on-chain in the last 24 hours? Highlight any unusually large transactions.',
    'What is the latest ETH gas fee? Compare Ethereum’s network activity to Bitcoin’s.',
    'Identify the largest Bitcoin whale transactions in the last 12 hours. Did any go to exchanges?',
    'What is the current MVRV Z-Score for Bitcoin? Does it signal a market top or bottom?',
    'Show the latest on-chain metrics for Ethereum. Compare key stats to Bitcoin and explain any trends.',
  ],
  'DeFi & Yield': [
    'Which DeFi protocol currently offers the highest stablecoin yield? Is the yield sustainable based on recent data?',
    'Compare the 7-day APY for ETH staking across Lido, Rocket Pool, and Coinbase. Which offers the best risk/reward?',
    'What is the liquidation risk for the top 3 MakerDAO vaults right now? Highlight any vaults at risk.',
    'List the DeFi protocols with the highest TVL growth this week. What’s driving the increase?',
    'Rank the top DeFi tokens by TVL. For each, compare their YTD return to Bitcoin.',
  ],
  'NFT & Social Analytics': [
    'What is the current floor price of the top NFT collection? How has it changed in the last week?',
    'Which NFT project had the most sales in the last 24 hours? Summarize the main drivers of activity.',
    'Show the most retweeted Bitcoin tweet in the last 24 hours. Summarize its impact on sentiment.',
    'List the top 3 trending topics on X (Twitter) in crypto right now. For each, explain why it’s trending.',
    'Summarize the latest crypto market news. Highlight any assets that are outperforming Bitcoin today.',
  ],
  'News & Events': [
    'List the top 3 breaking crypto news headlines right now. For each, explain its potential market impact.',
    'Which altcoin is getting the most media coverage today? Summarize the main story.',
    'Summarize the latest SEC or regulatory update affecting crypto. What is the likely impact on prices?',
    'List the top 3 upcoming crypto events. For each, predict its likely impact on the market.',
  ],
  'Portfolio & Strategy Simulation': [
    'If I bought $1,000 of BTC a week ago, what’s it worth now? Show the calculation.',
    'Backtest the best-performing DCA strategy for BTC this year. What was the optimal interval?',
    'Which altcoin rotation strategy would have outperformed BTC this month? Show the returns.',
    'Simulate a portfolio with 50% BTC, 25% NVDA, 25% ETH. How did it perform YTD?',
    'If I rotated from MSTR to BTC after each earnings report, what would my returns look like?',
    'How would a 60/40 BTC/SPY portfolio have performed during the last market drawdown?',
    'Calculate the Sharpe ratio of holding BTC vs Tesla over the last year. Which was better?',
    'Backtest a weekly DCA strategy for BTC vs SOL since January 2023. Which performed better?',
  ],
  'Event-Driven & Predictive': [
    'Based on current funding rates and open interest, is the market net long or short on BTC? Show supporting data.',
    'Which altcoin is most likely to benefit from the next Ethereum upgrade? Provide supporting metrics.',
    'List upcoming earnings or IPOs that could impact BTC correlation. Explain the likely effect.',
    'Are there any regulatory events or FOMC meetings this week? Predict their impact on Bitcoin and stocks.',
    'Which companies have the highest analyst upgrades this month? Compare their returns to BTC.',
    'List the most shorted stocks right now. How are they performing vs Bitcoin?',
    'What’s the best way to hedge a BTC-heavy portfolio ahead of earnings season? Provide actionable strategies.',
  ],
  'Risk & Downside': [
    'List the biggest risks to Bitcoin’s price this month. For each, explain the potential impact.',
    'How can I protect my portfolio if BTC drops 20% suddenly? Suggest actionable steps.',
    'Which altcoins are most correlated with BTC drawdowns? Show the correlation data.',
    'What is the historical max drawdown for BTC, ETH, and MSTR? Which asset recovered fastest?',
    'How do I set stop-losses or alerts for my BTC and stock holdings? Provide a step-by-step guide.',
  ],
  'Regulatory & Institutional': [
    'Summarize the latest SEC enforcement actions against crypto exchanges. How have they affected trading volumes?',
    'Which public companies increased their Bitcoin holdings this quarter? What’s their average entry price?',
    'What is the current state of spot Bitcoin ETF flows? How are they impacting price?',
    'Analyze insider sentiment for Apple. How does it compare to BTC price action?',
    'List the most recent institutional holdings changes for NVDA. Benchmark vs BTC.',
  ],
  // Advanced/power user prompts
  'Advanced Scenarios': [
    'If I rebalanced my portfolio weekly between BTC and the top S&P500 gainer, what would my YTD return be? Show the calculation.',
    'How would a 3-asset rotation (BTC, ETH, NVDA) based on momentum signals have performed since 2022?',
    'Simulate a scenario where BTC drops 30% and stocks rally. What happens to a 50/50 BTC/SPY portfolio?',
    'Rank the best-performing asset classes (crypto, stocks, gold) in the last 90 days. Explain the drivers.',
    'If I only bought assets with positive insider sentiment, how would my returns compare to BTC?',
  ],
  "Stock Trading Automation": [
    "Analyze the current trends in the stock market, focusing on [input sector or stock]. Identify any emerging patterns and suggest potential investment opportunities. Consider recent earnings reports and industry news in your analysis.",
    "Given a portfolio with a mix of [input current sectors or stocks], suggest strategies to diversify further while minimizing risk. Include potential sectors to explore and specific stocks to consider.",
    "Discuss effective risk management techniques for a stock trader. Provide detailed examples of how to implement stop-loss orders, diversification, and position sizing in a trading strategy. Use [input current trading strategy or stock] as a reference.",
    "Using technical analysis, evaluate the stock of [input stock]. Analyze recent price movements, volume, and key indicators such as moving averages and RSI. Provide a buy, sell, or hold recommendation.",
    "Explain how various economic indicators like GDP, unemployment rates, and inflation impact stock market performance. Provide examples of how investors can use these indicators to make informed trading decisions regarding [input sector or stock].",
    "Describe the principles of value investing and how to identify undervalued stocks. Use real-world examples, including [input stock or company], to illustrate how investors can apply this strategy in the current market.",
    "Analyze how market sentiment influences stock prices. Discuss tools and techniques investors can use to gauge sentiment and incorporate it into their trading strategies. Focus on [input stock or sector].",
    "Explain how to interpret a company's earnings report. Highlight the key metrics investors should focus on and how these metrics can impact stock prices. Use [input company's latest earnings report] as an example.",
    "Compare and contrast growth stocks and dividend stocks. Discuss the benefits and risks of each type of investment and suggest scenarios where one might be more suitable than the other. Reference [input specific growth stock and dividend stock].",
    "Analyze the impact of major global events (e.g., geopolitical tensions, pandemics) on the stock market. Provide strategies for investors to protect their portfolios during such events. Consider the impact on [input sector or stock]."
  ],
}; 